spring:
  application:
    name: xiangyu-backend
  profiles:
    active: dev
  datasource:
    username: root
    password: NXiang2002
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiangyu
  # redis配置
  redis:
    port: 6379
    host: localhost
    database: 0
  # session失效时间(分钟)
  session:
    #失效时间一天
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8080
  servlet:
    context-path: /api
  reactive:
    session:
      cookie:
        domain:
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted_flag # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
